# ------------------------------------------------------------------------------
# curl - unaltered, original
set(EXTRA_CURL_DEFS
  "/DCURL_STATICLIB /DNGHTTP2_STATICLIB /DNGHTTP3_STATICLIB /DNGTCP2_STATICLIB")
ExternalProject_Add(curl
  PREFIX ${PROJECT_NAME}/curl
  GIT_REPOSITORY https://github.com/curl/curl.git
  GIT_TAG "curl-8_19_0"
  GIT_PROGRESS FALSE
  CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${ONELUAPRO_BUILDROOT}"
  "-DBUILD_SHARED_LIBS=OFF"
  "-DBUILD_LIBCURL_DOCS=OFF"
  "-DBUILD_MISC_DOCS=OFF"
  "-DENABLE_CURL_MANUAL=OFF"
  "-DUSE_WIN32_IDN=ON"
  "-DENABLE_UNICODE=ON"
  "-DCURL_STATIC_CRT=ON"
  "-DBUILD_TESTING=OFF"
  "-DCURL_USE_LIBPSL=OFF"
  "-DCURL_USE_OPENSSL=ON"
  "-DUSE_NGTCP2=ON"
  "-DENABLE_ARES=OFF"
  "-DCURL_HIDDEN_SYMBOLS=OFF"
  "-DNGTCP2_USE_STATIC_LIBS=ON"
  "-DBUILD_EXAMPLES=OFF"
  "-DBUILD_CURL_EXE=OFF"
  "-DCURL_WINDOWS_SSPI=ON"
  "-DUSE_WIN32_CRYPTO=ON"
  "-DENABLE_THREADED_RESOLVER=ON"
  "-G${CMAKE_GENERATOR}"
  "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
  "-DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}"
  "-DCMAKE_C_FLAGS=${EXTRA_CURL_DEFS} ${SUPERBUILD_C_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_EXE_LINKER_FLAGS=${SUPERBUILD_EXE_LINKER_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_STATIC_LINKER_FLAGS=${SUPERBUILD_STATIC_LINKER_FLAGS}"
  ${GENERATOR_ARGS}
)
add_dependencies(curl zlib-ng libressl brotli zstd nghttp2 ngtcp2 nghttp3)
