# ------------------------------------------------------------------------------
# luautf8
#set(LUA_UTF8_VER "origin/master")
set(LUA_UTF8_VER "0.2.1-7-g3ae0b91")
ExternalProject_Add(luautf8
  PREFIX ${PROJECT_NAME}/luautf8
  GIT_REPOSITORY https://github.com/OneLuaPro/luautf8.git
  GIT_TAG ${LUA_UTF8_VER}
  GIT_PROGRESS FALSE
  CMAKE_ARGS "-DLUA_HINTS=${ONELUAPRO_BUILDROOT}"
  "-DCMAKE_INSTALL_PREFIX=${ONELUAPRO_PREFIX}"
  "-G${CMAKE_GENERATOR}"
  "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
  "-DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}"
  "-DCMAKE_C_FLAGS=${SUPERBUILD_C_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_EXE_LINKER_FLAGS=${SUPERBUILD_EXE_LINKER_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_SHARED_LINKER_FLAGS=${SUPERBUILD_SHARED_LINKER_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  ${GENERATOR_ARGS}
)
add_dependencies(luautf8 lua)
# Help Center registration
set_property(GLOBAL APPEND PROPERTY ONELUAPRO_DOC_LIST 
  "lua-utf8;lua-utf8/README.html;UTF-8 Support for Lua;💎;Core & Language;${LUA_UTF8_VER}"
)

