# ------------------------------------------------------------------------------
# nghttp3 - unaltered, original
ExternalProject_Add(nghttp3
  PREFIX ${PROJECT_NAME}/nghttp3
  GIT_REPOSITORY https://github.com/ngtcp2/nghttp3.git
  GIT_TAG "v1.15.0"
  GIT_PROGRESS FALSE
  CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${ONELUAPRO_BUILDROOT}"
  "-DENABLE_DEBUG=OFF"
  "-DENABLE_LIB_ONLY=ON"
  "-DENABLE_STATIC_LIB=ON"
  "-DENABLE_SHARED_LIB=OFF"
  "-DENABLE_STATIC_CRT=ON"
  "-DBUILD_TESTING=OFF"
  "-G${CMAKE_GENERATOR}"
  "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
  "-DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}"
  "-DCMAKE_C_FLAGS=${SUPERBUILD_C_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_EXE_LINKER_FLAGS=${SUPERBUILD_EXE_LINKER_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_STATIC_LINKER_FLAGS=${SUPERBUILD_STATIC_LINKER_FLAGS}"
  ${GENERATOR_ARGS}
)
