# ------------------------------------------------------------------------------
# ngtcp2 - unaltered, original
ExternalProject_Add(ngtcp2
  PREFIX ${PROJECT_NAME}/ngtcp2
  GIT_REPOSITORY https://github.com/ngtcp2/ngtcp2.git
  GIT_TAG "v1.21.0"
  GIT_PROGRESS FALSE
  CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${ONELUAPRO_BUILDROOT}"
  "-DENABLE_SHARED_LIB=OFF"
  "-DENABLE_LIB_ONLY=ON"
  "-DBUILD_TESTING=OFF"
  "-DENABLE_OPENSSL=ON"
  "-G${CMAKE_GENERATOR}"
  "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
  "-DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}"
  "-DCMAKE_C_FLAGS=${SUPERBUILD_C_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_EXE_LINKER_FLAGS=${SUPERBUILD_EXE_LINKER_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_STATIC_LINKER_FLAGS=${SUPERBUILD_STATIC_LINKER_FLAGS}"
  ${GENERATOR_ARGS}
)
add_dependencies(ngtcp2 libressl)
