# ------------------------------------------------------------------------------
# vscode-lua-cmake
#set(VSCODE_LUA_CMAKE_VER "origin/master")
set(VSCODE_LUA_CMAKE_VER "v3.18.2-0")
ExternalProject_Add(vscode-lua-cmake
  PREFIX ${PROJECT_NAME}/vscode-lua-cmake
  GIT_REPOSITORY https://github.com/OneLuaPro/vscode-lua-cmake.git
  GIT_TAG ${VSCODE_LUA_CMAKE_VER}
  GIT_PROGRESS FALSE
  CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=${ONELUAPRO_PREFIX}"
  "-DCODE_SIGN_ID=${CODE_SIGN_ID}"
  "-DSIGN_PACKAGE=ON"
  "-G${CMAKE_GENERATOR}"
  "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
  "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}"
  "-DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}"
  "-DCMAKE_C_FLAGS=${SUPERBUILD_C_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_CXX_FLAGS=${SUPERBUILD_CXX_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_EXE_LINKER_FLAGS=${SUPERBUILD_EXE_LINKER_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  "-DCMAKE_SHARED_LINKER_FLAGS=${SUPERBUILD_SHARED_LINKER_FLAGS} ${SUPERBUILD_IPO_OPTS}"
  ${GENERATOR_ARGS}
)
